CREATE TABLE PROVINCE(
PROVINCE_ID INT IDENTITY(1,1) PRIMARY KEY,
PROVINCE_NAME NVARCHAR(10)
)
CREATE TABLE TOWN(
TOWN_ID INT IDENTITY(1,1) NOT NULL,
PROVINCE_ID INT NOT NULL,
TOWN_NAME NVARCHAR(10),
PRIMARY KEY (TOWN_ID , PROVINCE_ID),
CONSTRAINT FK_PV FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE(PROVINCE_ID)
)
CREATE TABLE ROLE(
ROLE_ID INT IDENTITY(1,1) PRIMARY KEY,
ROLE_NAME NVARCHAR(50)
)
CREATE TABLE USERS(
USER_ID INT IDENTITY(1,1) PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PASSOWORD VARCHAR(50) NOT NULL,
USER_STATUS INT ,
ROLE_ID INT ,
JOINED_DATE VARCHAR(10),
FACEBOOK_ID VARCHAR(100),
GMAIL_ID VARCHAR(100)
CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
)
CREATE TABLE PROFILE(
PROFILE_ID INT IDENTITY(1,1) PRIMARY KEY,
USER_ID INT NOT NULL,
FIRST_NAME NVARCHAR(50),
LAST_NAME NVARCHAR(50),
BIRTHDAY VARCHAR(10),
SEX VARCHAR(10),
EMAIL VARCHAR(50),
PHONE INT,
TOWN_ID INT,
ADDRESS NVARCHAR(100),
AVATAR VARCHAR(100),
DESCRIPTION NVARCHAR(255),
CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
CONSTRAINT FK_TOWN1 FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID)
)